### ISSUE TITLE
Fix Observation Space lows and highs

### ISSUE THREAD

**Issue by taapasX28** [taapasX28/HumanoidRL#6]
The current values of highs and lows for `bodyPos` is completely random which results in bot jumping around during training. Fix these values.

**Comment by Shivanshmundra** [comment]
@taapasX28  any idea how to fix this? We discussed on this by recording values and taking min and max cumulatively.

**Comment by taapasX28** [comment]
My bad the values for only `bodyPos` is random (Assigned 10, 10, 10 and -10,-10, -10 in terms of X, Y, Z). An approach could be printing these values for the bot in standing position and then add suitable deviations.
