### ISSUE TITLE
Value error in running policy post training

### ISSUE THREAD

**Issue by taapasX28** [taapasX28/HumanoidRL#7]
After training when we test policy we encounter an error of the form `ValueError: could not broadcast input array from shape (n,1) into shape (n)` . This needs a permanent fix. According to @Shivanshmundra current fix at the bottom of README doesn't work for everyone. So a permanent fix needed. See discussion: https://krssg-research.slack.com/archives/GH77FQ93J/p1586497799000100?thread_ts=1586426170.003800&cid=GH77FQ93J

**Comment by sriyash421** [comment]
The test_policy script was written for an older version of spinup. The functions called by test_policy.py are deprecated.
